version: "3.8"
services:
  bot:
    build: .
    container_name: my-bot
    ports:
      - "3000:3000"   # Map container port 3000 to host port 3000
    restart: always   # Automatically restart on failure


